### ISSUE TITLE
tests fail on windows

### ISSUE THREAD

**Issue by katmratliff** [UNCG-DAISY/psi-collect#102]
**Describe the bug**
test_cataloging.py fails on Win32 Python 3.7.3

**To Reproduce**
run pytest in root directory produces this:
![image](https://user-images.githubusercontent.com/12630578/74981825-f7a8f600-5400-11ea-8b98-ff4a6b7dcd01.png)

**Additional context**
I noticed that Travis was only set up to run in a linux env, so feel free to close this issue if you aren't worried about testing on Windows, just wanted you all to be aware that I had tried to run them and what the result was.

Note: Submitting this issue as part of the JOSS review process (openjournals/joss-reviews#2075)

**Comment by Matmorcat** [comment]
It looks like you're running it in a Conda environment which likely has an
older version of pandas. Have you tried it with pipenv, making sure to
include the project directory in your PYTHONPATH environment variable?

**Comment by chrisleaman** [comment]
@katmratliff, I was able to get `pytest` running in my Windows environment so I think you're experiencing some issue with your local environment? Perhaps check you're using the latest version of numpy (see [this issue](https://github.com/scikit-learn-contrib/hdbscan/issues/272)).

**Comment by katmratliff** [comment]
@Matmorcat yes I was testing in a conda env. If @chrisleaman had no issues running the tests on windows then I will close this - thanks!
