### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/psi-collect#21]
I don't have experience with docs, but the home page of the docs is not the same as the README.md, which it should be:

for example, the team order is different, the USGS data page is still listed, and many of the internal docs links on the home page are routed to the old documents.

**Comment by ebgoldstein** [comment]
@Matmorcat , can you add me as an admin in the psi-collect readthedocs so i can refresh the build

**Comment by ShahNafisRafique** [comment]
currently readthedocs is broken because they had a buffy update to pip 20 ,read more [here](https://github.com/readthedocs/readthedocs.org/issues/6554)

**Comment by Matmorcat** [comment]
@ebgoldstein I added you as a maintainer, you should be able to login using your Github at https://readthedocs.org/

As Shah said, the host has a critical bug right now that's affecting us, so we have to wait and see when they'll fix it.

**Comment by ebgoldstein** [comment]
thx @Matmorcat ! I'm going to close this up...

**Comment by Matmorcat** [comment]
@ebgoldstein I got the docs fixed. There was an issue with the webhook not sending updates from github to readthedocs, so it wasn't building the latest changes. I also re-added the index.md, since it essentially acts as a link to the current README.md, and without it, the docs cannot find the README (since it exists outside the /docs folder).

psi-collect is not affected by the bug Shah mentioned :)

**Comment by ebgoldstein** [comment]
thx @Matmorcat !! I was fiddling with the index, a few nights ago, sorry...

**Comment by ebgoldstein** [comment]
also:
>There was an issue with the webhook not sending updates from github to readthedocs

Which commit fixed this? I want to see where this is

**Comment by Matmorcat** [comment]
There is no commit for it. I registered a new webhook in GitHub under the
repo's settings, under the Webhooks tab using the webhook's URL under
readthedoc's integrations tab and gave it public read, public write, and
push access.
