### ISSUE TITLE
add more detail to paper.md

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/psi-collect#62]
> I would recommend adding a bit more motivation to the paper.md. Based on our conversation at AGU I know that there many qualities of this package that make collection and cataloging of images way easier, probably more appropriately described as actually possible. This doesn't come through clearly in the paper. I would recommend expanding the statement of need and/or adding a section that focuses on challenges to accessing this dataset that sets up the statement of need.

from: 
https://github.com/openjournals/joss-reviews/issues/2064#issuecomment-581974815

@Matmorcat I will add text, but if you have any specific ideas, pls feel free to add or ping me.

**Comment by Matmorcat** [comment]
@ebgoldstein I'd say to just include elaboration about how the download of archives tended to freeze or terminate regularly throughout attempting to download. There are other software that can resume partial downloads (including Firefox's downloading), but will either not continue when a problem arises that can be solved (Firefox) or they are not able to intelligently handle the actual scraping of the archives for our particular use case (most require you to manually select what you want to download and do not scan multiple levels of pages).

Our program stops at the appropriate depth to capture all of the data archives without unnecessarily scanning further pages, as that would increase the time and bandwidth requirement for finding archives at an increasing rate as you traverse deeper, and would introduce loops (e.g. page A links to page B links to page C links to page A).

**Comment by ebgoldstein** [comment]
thanks @Matmorcat — your text helps alot. The NGS folks suggested:

`wget -T 3600 --no-http-keep-alive` 

but this seems suboptimal as one would still need to supply the address for each image tar or ZIP

**Comment by Matmorcat** [comment]
Yes, good example. That command will correct for timeouts, but does not traverse pages dynamically (meaning it would not work for the older archives), and it doesn't allow for finding archives for a storm unless you manually select their download URLs.

**Comment by Matmorcat** [comment]
@ebgoldstein Also, we may have overlooked the importance of the locking mechanism for some teams. In the process of downloading the data for our own uses, we implemented a soft locking mechanism that allowed us to download the archives from multiple computers to our team drive. This could be used with almost any network file system or distributed file systems like Hadoop in which multiple computers would need to download to the same location without stepping on each other's feet.

The locking system creates a text file named the same as the archive, but with the additional ending '.lock' (eg. 'xxxx.tar.lock') that contains information about what user is downloading that archive, their progress, and how large it will be when done downloading (and fully uploaded). It then updates this file regularly as the download progresses for the downloading user.

**Comment by ebgoldstein** [comment]
@Matmorcat,  here is some new text (👇 ). I think we might remove the fourth (?) since its specific to us... (@kbarnhart, patching you in for a look to see if this is what you are after) 

👇 👇 👇 👇 👇 👇 👇 

`psi-collect` works to address four issues that enable researchers to work with large collections of NOAA post storm aerials. 

First, Users previously needed to manually navigate to each storm and individually download the multiple image tar / zip files. Download could be done with the graphical user interface, or via another technique (e.g. `wget` on Linux). Even though `wget` is a command line method for retrieving the data, users would still be required to manually navigate and include individual web addresses for each storm archive (there are 15 individual archives for Hurricane Florence). `psi-collect` dynamically traverses pages and downloads archives when given specific filtering/sub-setting criteria (i.e. downloading all archives from Hurricane Florence)

Second, the individual image archives are large, and often freeze or terminate during download. Some browsers or software tools may be capable of resuming partial downloads, but this is case specific and depends on the retrieval workflow. Terminated downloads may require users to determine the missing archive, and re-initiate a download. `psi-collect` has an automatic resumption feature in the event that a download is interrupted. Additionally, tar and zip archives are checked for the integrity of the contents upon download completion to ensure that the included data are accurate and intact.

Third, we have observed that download speeds can be slow. `psi-collect` handles queuing of downloads, and cataloging what downloads exist on a user's local computer. These are useful features when multiple archives are needed.

Fourth, `psi-collect` implements a soft locking mechanism allowing users to simultaneously download archives on multiple computers that upload to a single network file system or integrate with a distributed file systems (e.g. Hadoop). The locking system creates a text file named the same as the archive, but with an additional ending (e.g. 'xxxx.tar.lock') containing information about what user is downloading that archive, their progress, and how large it will be when done downloading (and fully uploaded). It then updates this file regularly as the download progresses.

**Comment by Matmorcat** [comment]
I'd say keep the 4th as it is a discrete feature built in, and may be very useful when it comes to surpassing the limit of one computer's network. DFSs are also used for distributed computation w/ Spark and other systems when working with big data, so it might not be unreasonable that some may use such a feature for its ease of use.

@ebgoldstein I made some slight grammar / spelling changes above, you can see the changes by clicking on my username where it says `edited by Matmorcat`

**Comment by kbarnhart** [comment]
@ebgoldstein I think the new text looks good! Thanks for revising.

**Comment by chrisleaman** [comment]
This added detail looks good 👍 Can you merge into the paper and I'll finish up my review?

**Comment by ebgoldstein** [comment]
added: https://github.com/UNCG-DAISY/psi-collect/commit/d614cdd1bae826850d38a9726a65b2b25c7d9f5f

(cc: @chrisleaman )
