### ISSUE TITLE
Version for JOSS submission is listed incorrectly

### ISSUE THREAD

**Issue by Matmorcat** [UNCG-DAISY/psi-collect#72]
The version for JOSS submission labelled as v0.6, when the latest software release is currently v1.0.0 (pypi and otherwise).

**Comment by ebgoldstein** [comment]
hmm.... i think we can clear that up at the end of review... I'll keep this open and loop back at the 'proof' stage if we make it thorugh review

**Comment by kbarnhart** [comment]
I can confirm that you will be asked to provide a final version number.
