### ISSUE TITLE
Cannot specify path for pstorm catalog

### ISSUE THREAD

**Issue by chrisleaman** [UNCG-DAISY/psi-collect#73]
**Describe the bug**
`pstorm catalog` expects the downloaded data to only be at `<user_home>/psi/collect/data/archives`. If the user specifies another location to download the files to (`pstorm collect --path C:\data\`), there is no way to specify this path and `pstorm catalog` cannot find the data.

**To Reproduce**
1. `pstorm collect -s Florence --path C:\data\ --download`.
2. `pstorm catalog -e tif`

**Expected behavior**
Either one of two options could work:
1. Remove `--path` option from `pstorm collect`. Data will always be downloaded to `<user_home>/psi/collect/data/archives`
2. Add `--path` option to `pstorm catalog` so user can specify where data is located.

**Comment by Matmorcat** [comment]
I've added the `--path` as an alternative way to tell it to catalog starting in a specific path. The way it works is that it uses the directory the command is run from as the source for the data, but the documentation did not explain that!

I've updated the documentation to reflect this information.

**Comment by chrisleaman** [comment]
Linking to https://github.com/openjournals/joss-reviews/issues/2075
