### ISSUE TITLE
Cataloging function not working for multiple storms?

### ISSUE THREAD

**Issue by conlin-matt** [UNCG-DAISY/psi-collect#96]
**Describe the bug**
The cataloging function doesn't seem to work for a number of storms, possibly because these storms don't ship with .geom files? I have had issues with Sandy, Maria, Irma, and Irene. I notice that none of these seem to come with .geom files for their images (whereas storms such as Dorian and Gordon do). 

**To Reproduce**
1. pstorm collect -s Sandy -a oct31ajpeg (or Irma or Maria etc.) -d
   *Notice the lack of .geom files
2. pstorm catalog -p .../Sandy (or Irma or Maria etc.)

**Expected behavior**
The catalog csv file should be produced.

**Screenshots**
I get this error message when trying to catalog images for Irma
![Screen Shot 2020-02-18 at 9 55 35 AM](https://user-images.githubusercontent.com/32144021/74747389-e4492f80-5234-11ea-8ea0-684089294196.png)

**Additional context**
This seems similar to #74 . Am I missing something here, e.g. downloading the images incorrectly so that the .geom files don't ship? 

Note: Submitting this issue as part of the JOSS review process (openjournals/joss-reviews#2075)

**Comment by ebgoldstein** [comment]
yes, unfortunately those storms didn't ship with raw `jpg`s, and therefore they don't have `.geom` files. Sandy has `jpg`s, but they are jpg tiles, so don't have associated
 `.geom` file separately.
I will add a note in the docs that cataloging the coordinates only work when storms have `.geom` files. there has been change every few years in what products are distributed.

**Comment by conlin-matt** [comment]
Ok, that's what I figured. I agree that having that note in the docs is important in order to be transparent about what the tool can do, so glad to see it added.

**Comment by ebgoldstein** [comment]
i'm reopening this until i make the changes in the docs

**Comment by katmratliff** [comment]
@ebgoldstein I've also noticed that when running `pstorm catalog` on a folder without `.geom` files can generate a `.csv` file that has an incorrect storm name... e.g., running on a folder on my desktop creates a `Desktop.csv` catalog file that also has the `storm_id` labeled as `desktop`. I've tested in different locations and end up with other incorrect catalog/`storm_id` names. Guessing this is similar to the path recursion issues in #74 (and I am also running on Windows). Maybe best to terminate generating a `csv` if there are no `.geom` files?

**Comment by ebgoldstein** [comment]
thx for checking this @katmratliff. i think your suggestion — to terminate `.csv` generation when no `.geom` files exist — is the best way forward here.

**Comment by Matmorcat** [comment]
In the original post, @conlin-matt mentioned some storms that did not match the way the program identifies archives. I've changed the archive search to look for the parent directory being a valid storm name instead of matching arbitrary characters (original had to match a `20` and a `_` anywhere in the archive name). This should resolve the issue! 

Make sure to **delete the old catalog** for the storms that had issues, before running again with the new changes.

**Comment by ebgoldstein** [comment]
docs now state that Lat/Lon in catalog relies on `.jpg` and `.geom` : https://github.com/UNCG-DAISY/psi-collect/commit/23a43dad392ac9c78733ef39a6b0ba629e1612a8
