### ISSUE TITLE
Add feedback when no storm search term identified

### ISSUE THREAD

**Issue by katmratliff** [UNCG-DAISY/psi-collect#99]
**Is your feature request related to a problem? Please describe.**
Add short print statement when a storm search term or pattern is not found

**Describe the solution you'd like**
example response:
```
> pstorm collect -s katherine
Download Status Report (February 19, 2020 at 08:04 AM) <-s katherine -t .* -p C:\Users\<USER>\psi\collect\data\archives>

<No storms matching search term detected>
```

This is consistent with the feedback given when no archive files are detected for a specific search term or pattern.

**Comment by katmratliff** [comment]
Note: Submitting this issue as part of the JOSS review process (openjournals/joss-reviews#2075)

**Comment by Matmorcat** [comment]
You're right! I've added a message now when no storms match the search term. Added in a direct commit to master.
